[env]
TERM = "xterm-256color"

[window]
blur = true
opacity = 0.96
# startup_mode = "Maximized"
dynamic_padding = false
decorations = "None"
resize_increments = false
padding.y = 0
padding.x = 0

[font]
normal = { family = "MesloLGMDZ Nerd Font", style = "Regular" }
size = 7.2
offset.x = 0
offset.y = 0
builtin_box_drawing = true

[scrolling]
history = 1000
multiplier = 3

[mouse]
hide_when_typing = true
