set background=dark
set clipboard=unnamed
set colorcolumn=80
set encoding=UTF-8
set et
set expandtab
set hidden
set incsearch
set laststatus=2
set nobackup
set noerrorbells
set nowrap
set number
set numberwidth=1
set relativenumber
set rnu
set shiftwidth=2
set showcmd
set showmatch
set smartindent
set sts=4
set tabstop=2
set undodir=~/.vim/undodir
set undofile
set viminfo=""
